const FoodData = [
    {
        id: 1,
        type: 'Biryani',
        imgUrl: 'https://media.istockphoto.com/id/1305451864/photo/biryani.jpg?s=612x612&w=0&k=20&c=myS23vJLtxpHp3LSRm0NU3rU30s8aLb45UHs8mfY8KA=',
        name: 'Shahih Chicken Biryani',
        price: 250,
        currency: 'INR',
        ratings: 4.5,
        description: 'Aromatic rice dish cooked with chicken and spices.',
        netQuantity: '500g',
        type: 'non-veg',
    },
    {
        id: 2,
        type: 'Pizzas & Burgers',
        imgUrl: 'https://media.istockphoto.com/id/184946701/photo/pizza.jpg?s=612x612&w=0&k=20&c=97rc0VIi-s3mn4xe4xDy9S-XJ_Ohbn92XaEMaiID_eY=',
        name: 'Margherita Pizza',
        price: 160,
        currency: 'INR',
        ratings: 4.2,
        description: 'Classic pizza topped with tomato sauce, mozzarella cheese, and basil leaves.',
        netQuantity: 'Large',
        type: 'veg',
    },
    {
        id: 3,
        type: 'Snacks',
        imgUrl: 'https://media.istockphoto.com/id/174912622/photo/salmon-dinner.jpg?s=612x612&w=0&k=20&c=nsbN8HstWdLIkSaoEnN5xporkW7-Uqgycfv3p_mz5eA=',
        name: 'Grilled Salmon',
        price: 150,
        currency: 'INR',
        ratings: 4.8,
        description: 'Fresh salmon fillet grilled to perfection, served with roasted vegetables.',
        netQuantity: '200g',
        type: 'non-veg',
    },
    {
        id: 4,
        type: 'Biryani',
        imgUrl: 'https://media.istockphoto.com/id/179085494/photo/indian-biryani.jpg?s=612x612&w=0&k=20&c=VJAUfiuavFYB7PXwisvUhLqWFJ20-9m087-czUJp9Fs=',
        name: 'Vegetable Biryani',
        price: 180,
        currency: 'INR',
        ratings: 4.3,
        description: 'Delicious rice dish cooked with mixed vegetables and aromatic spices.',
        netQuantity: '400g',
        type: 'veg',
    },
    {
        id: 5,
        type: 'Pizzas & Burgers',
        imgUrl: 'https://media.istockphoto.com/id/1309352410/photo/cheeseburger-with-tomato-and-lettuce-on-wooden-board.jpg?s=612x612&w=0&k=20&c=lfsA0dHDMQdam2M1yvva0_RXfjAyp4gyLtx4YUJmXgg=',
        name: 'Cheese Burger',
        price: 130,
        currency: 'INR',
        ratings: 4.6,
        description: 'Juicy beef patty topped with melted cheese, lettuce, and tomato, served in a bun.',
        netQuantity: 'Single',
        type: 'non-veg',
    },
    {
        id: 6,
        category: 'Curries',
        imgUrl: 'https://media.istockphoto.com/id/1355695225/photo/paneer-masala-a-curry-made-with-cottage-cheese-cubes-cooked-in-a-gravy-of-onions-tomatoes-and.jpg?s=612x612&w=0&k=20&c=E76hpUAiTetGNgjhD3jkKNRV9ThePlUR87fPOeHDZyY=',
        name: 'Paneer Tikka Masala',
        price: 180,
        currency: 'INR',
        ratings: 4.4,
        description: 'Creamy tomato-based curry with grilled paneer cubes, seasoned with Indian spices.',
        netQuantity: '300g',
        type: 'veg',
    },
    {
        id: 7,
        category: 'Desserts',
        imgUrl: 'https://media.istockphoto.com/id/157619904/photo/multi-flavor-ice-cream-in-glass-bowi.jpg?s=612x612&w=0&k=20&c=0t5htAeazuT_GhFyd5phRe44tvADhTG7UNQlx5Smw4E=',
        name: 'Multi-Flavored Delight',
        price: 120,
        currency: 'INR',
        ratings: 4.9,
        description: 'Indulge in the ultimate ice cream experience with a combination of chocolate, butterscotch, and vanilla flavors, adorned with luscious strawberry and chocolate cream.',
        netQuantity: '550ml',
        type: 'veg',
    },
    {
        id: 8,
        category: 'Snacks',
        imgUrl: 'https://media.istockphoto.com/id/1221224008/photo/carbonara-pasta-penne-with-pancetta-egg-parmesan-cheese-and-cream-sauce.jpg?s=612x612&w=0&k=20&c=1yuTlk4bXbJU7YC-X9Ach8tT7bS1gERuLgh_BpDlHgw=',
        name: 'Pasta Carbonara',
        price: 70,
        currency: 'INR',
        ratings: 4.5,
        description: 'Spaghetti pasta tossed in a creamy sauce with crispy bacon and Parmesan cheese.',
        netQuantity: 'Large',
        type: 'non-veg',
    },
    {
        id: 9,
        category: 'Desserts',
        imgUrl: 'https://media.istockphoto.com/id/155598375/photo/dessert-chocolate-cake.jpg?s=612x612&w=0&k=20&c=DbBk025te405Suf8zNBdgp67y3iJB9LsyXERPQMTAqY=',
        name: 'Chocolate Fudge',
        price: 120,
        currency: 'INR',
        ratings: 4.8,
        description: 'Rich chocolate ice cream swirled with fudge sauce and chocolate chunks.',
        netQuantity: '400ml',
        type: 'veg',
    },
    {
        id: 10,
        category: 'Snacks',
        imgUrl: 'https://media.istockphoto.com/id/1369101558/photo/plate-of-barbecue-chicken-wings-top-view.jpg?s=612x612&w=0&k=20&c=cFFVf7PwTtcIgOFsIVh4gOlCr-lyzhUhH9Y91e8Sr0Q=',
        name: 'Barbecue Chicken Wings',
        price: 180,
        currency: 'INR',
        ratings: 4.2,
        description: 'Delicious barbecue chicken wings, perfect for snacking or as an appetizer.',
        netQuantity: 'Single',
        type: 'non-veg'
    },
    {
        id: 11,
        category: 'Salads',
        imgUrl: 'https://media.istockphoto.com/id/1178577651/photo/caesar-salad-vegetable-salad-with-roast-chicken-meat-on-wooden-background.jpg?s=612x612&w=0&k=20&c=LDEF3US51D55W8BHuSHp2mvKaw8nIhnv8bEyuyIWQC8=',
        name: 'Chicken Caesar Salad',
        price: 130,
        currency: 'INR',
        ratings: 4.6,
        description: 'Fresh romaine lettuce topped with grilled chicken breast, croutons, Parmesan cheese, and Caesar dressing.',
        netQuantity: 'Regular',
        type: 'non-veg',
    },
    {
        id: 13,
        category: 'Desserts',
        imgUrl: 'https://media.istockphoto.com/id/484951637/photo/creme-brulee.jpg?s=612x612&w=0&k=20&c=n3NezoWuYZMqzFxkcYS_QesVl1QDa547WJmv7Fumono=',
        name: 'Crème Brûlée',
        price: 100,
        currency: 'INR',
        ratings: 4.7,
        description: 'Classic French dessert consisting of rich custard topped with caramelized sugar, served chilled.',
        netQuantity: 'Single',
        type: 'veg',
    },
    {
        id: 14,
        category: 'Pastries',
        imgUrl: 'https://media.istockphoto.com/id/1287156261/photo/macarons-in-all-colors.jpg?s=612x612&w=0&k=20&c=Up8_WKO1MBonH6Kpn4HffcRcOtPkVvoUOIZdB6ieHfw=',
        name: 'Assorted Macarons',
        price: 20,
        currency: 'INR',
        ratings: 4.5,
        description: 'A selection of colorful and delicate French macarons with various flavors.',
        netQuantity: 'Box of 6',
        type: 'veg',
    },
    {
        id: 15,
        category: 'Asian Cuisine',
        imgUrl: 'https://media.istockphoto.com/id/185009280/photo/red-bowl-of-delicious-chicken-teriyaki.jpg?s=612x612&w=0&k=20&c=sE2EXs6B5nZYkp6BjSJ6ddXhkz9GVD58-7-_WQvFPJ0=',
        name: 'Chicken Teriyaki',
        price: 230,
        currency: 'INR',
        ratings: 4.4,
        description: 'Grilled chicken marinated in a sweet and savory teriyaki sauce, served with rice and vegetables.',
        netQuantity: 'Regular',
        type: 'non-veg',
    },
    {
        id: 16,
        category: 'Indian Cuisine',
        imgUrl: 'https://media.istockphoto.com/id/1169639937/photo/vegetarian-thali-indian-appetizers-and-snacks-pakora-samosas-and-bhaji-served-with-chutneys.jpg?s=612x612&w=0&k=20&c=LjBe9pUDNIE2WXucU_45GZ8_QR0CBi_6Cgc4uIrgkLw=',
        name: 'Vegetarian Thali',
        price: 250,
        currency: 'INR',
        ratings: 4.4,
        description: 'A traditional Indian meal served on a platter, consisting of a variety of vegetarian dishes such as dal, sabzi, roti, rice, and dessert.',
        netQuantity: 'Full Plate',
        type: 'veg',
    },
    {
        id: 17,
        category: 'Curries',
        imgUrl: 'https://media.istockphoto.com/id/1005390222/photo/chicken-tikka-masala-spicy-curry-meat-food-with-rice-and-naan-bread.jpg?s=612x612&w=0&k=20&c=UPKJT67Bn-2ZL1TakWLK9IhpAOIMgryGhLwoHRsP8ZI=',
        name: 'Chicken Tikka Masala',
        price: 160,
        currency: 'INR',
        ratings: 4.7,
        description: 'Tender chicken pieces marinated in spices and yogurt, grilled and served in a creamy tomato-based sauce, accompanied by rice.',
        netQuantity: 'Full Plate',
        type: 'non-veg',
    },
    {
        id: 18,
        category: 'Snacks',
        imgUrl: 'https://media.istockphoto.com/id/1225269816/photo/samsa-on-a-dark-background-traditional-eastern-uzbek-pastries-triangular-meat-pies-the-view.jpg?s=612x612&w=0&k=20&c=zkg3OAWbGFgTeEWoZmXqEFMJow0Ox8rVB6mA2kTnhn4=',
        name: 'Vegetable Samosa',
        price: 10,
        currency: 'INR',
        ratings: 4.2,
        description: 'Crispy pastry filled with spiced potatoes, peas, and other vegetables, served with chutney.',
        netQuantity: 'Single',
        type: 'veg',
    },
    {
        id: 20,
        category: 'Indian Cuisine',
        imgUrl: 'https://media.istockphoto.com/id/851889508/photo/palak-paneer.jpg?s=612x612&w=0&k=20&c=5xcTOeOYTnihYzSG4OYaLVkhgn1EOgehU73aiZnhhNA=',
        name: 'Palak Paneer',
        price: 180,
        currency: 'INR',
        ratings: 4.5,
        description: 'Creamy spinach curry with chunks of paneer (Indian cottage cheese), seasoned with spices.',
        netQuantity: 'Regular',
        type: 'veg',
    },
    {
        id: 21,
        category: 'Break-fast',
        imgUrl: 'https://media.istockphoto.com/id/1374666267/photo/masala-dosa-south-indian-breakfast.jpg?s=612x612&w=0&k=20&c=wHurZpgJCahFgRIVwaSH46l0_NAWFFLRJp3JY5-obqc=',
        name: 'Masala Dosa',
        price: 70,
        currency: 'INR',
        ratings: 4.3,
        description: 'Thin crepe made from fermented rice and lentil batter, filled with a spicy potato filling, served with chutney and sambar.',
        netQuantity: 'Single',
        type: 'veg',
    },
    {
        id: 22,
        category: 'Break-fast',
        imgUrl: 'https://media.istockphoto.com/id/979914742/photo/chole-bhature-or-chick-pea-curry-and-fried-puri-served-in-terracotta-crockery-over-white.jpg?s=612x612&w=0&k=20&c=OLAw-ZleN1UVaa468OlPSAc6dkz2sjehxWevbvZQNew=',
        name: 'Chole Bhature',
        price: 80,
        currency: 'INR',
        ratings: 4.6,
        description: 'Spicy chickpea curry (chole) served with deep-fried bread (bhature), accompanied by onions and pickles.',
        netQuantity: 'Single Plate',
        type: 'veg',
    },
    {
        id: 23,
        category: 'Indian Cuisine',
        imgUrl: 'https://media.istockphoto.com/id/953514746/photo/tandoori-chicken-whole-with-naan-and-raita.jpg?s=612x612&w=0&k=20&c=1IaMUgHNJwf8-h6XnzoiW64E0v_TxGhOItUQL9dwzRE=',
        name: 'Tandoori Chicken',
        price: 200,
        currency: 'INR',
        ratings: 4.8,
        description: 'Marinated chicken roasted in a tandoor (clay oven), served with mint chutney and salad.',
        netQuantity: 'Half',
        type: 'non-veg',
    },
    {
        id: 24,
        category: 'Curries',
        imgUrl: 'https://media.istockphoto.com/id/1217568305/photo/kashmiri-rogan-josh.jpg?s=612x612&w=0&k=20&c=B3VO0bafV9P5KA4FET_RjyAS0QtF9VXDhz0kvSJERqk=',
        name: 'Mutton Rogan Josh',
        price: 180,
        currency: 'INR',
        ratings: 4.7,
        description: 'Spicy curry made with tender mutton cooked with a blend of aromatic spices, garnished with fresh coriander.',
        netQuantity: 'Regular',
        type: 'non-veg',
    },
    {
        id: 25,
        category: 'Curries',
        imgUrl: 'https://media.istockphoto.com/id/669656212/photo/kidney-bean-curry-or-rajma-or-rajmah-chawal-and-roti-typical-north-indian-main-course.jpg?s=612x612&w=0&k=20&c=O-jLp0X-OmOXjpMg969mr-DvVwReO948RXeRgKM6OK0=',
        name: 'Rajma Masala',
        price: 120,
        currency: 'INR',
        ratings: 4.4,
        description: 'Spicy red kidney bean curry cooked with onions, tomatoes, and a blend of Indian spices.',
        netQuantity: 'Regular',
        type: 'veg',
    },
    {
        id: 26,
        category: 'Sweets',
        imgUrl: 'https://media.istockphoto.com/id/980090836/photo/rice-pudding-or-kheer-from-india-called-also-called-firnee-served-in-a-bowl-selective-focus.jpg?s=612x612&w=0&k=20&c=zSim-PRNtIL6NKrVooZYlqjKXi6O-Kl9wb8bueD0-yI=',
        name: 'Mujafar Kheer',
        price: 100,
        currency: 'INR',
        ratings: 4.5,
        description: 'A traditional Indian sweet made from fine vermicelli, sugar syrup, and garnished with nuts and saffron.',
        netQuantity: '250g',
        type: 'veg',
    },
    {
        id: 27,
        category: 'Indian Cuisine',
        imgUrl: 'https://media.istockphoto.com/id/1292894204/photo/haneeth-is-a-traditional-yemeni-dish-also-trendy-in-the-rest-of-the-arabian-peninsula-closeup.jpg?s=612x612&w=0&k=20&c=FIGWJIYH18mxe3SEKiP1WZanPiA1UXyes0452-LMPmM=',
        name: 'Shahi Mutton Mandi',
        price: 350,
        currency: 'INR',
        ratings: 4.6,
        description: 'A royal dish made with tender mutton pieces cooked with aromatic spices, basmati rice, and Sgarnished with fried onions, nuts, and raisins.',
        netQuantity: 'Full Plate',
        type: 'non-veg',
    },
    {
        id: 28,
        category: 'Curries',
        imgUrl: 'https://media.istockphoto.com/id/890466990/photo/lamb-shank-or-mutton-or-gosht-paya-or-khoor-curry-served-with-indian-bread-or-roti-or-naan.jpg?s=612x612&w=0&k=20&c=7yECFWyWGSkIlGluag7n-PKzoXTmI2HLhBQXR1LWOQc=',
        name: 'Nihari',
        price: 150,
        currency: 'INR',
        ratings: 4.7,
        description: 'Slow-cooked beef stew seasoned with spices, typically served with naan bread.',
        netQuantity: 'Regular Bowl',
        type: 'non-veg',
    },
    {
        id: 29,
        category: 'Biryani',
        imgUrl: 'https://media.istockphoto.com/id/1333124219/photo/mutton-biryani-chicken-biryani-spicy-indian-malabar-biryani-hyderabadi-biryani-dum-biriyani.jpg?s=612x612&w=0&k=20&c=dh5quqpgbqAwSICJPAvUKiSNILtEKFMkSED8op1vsyI=',
        name: 'Karachi Beef Biryani',
        price: 220,
        currency: 'INR',
        ratings: 4.8,
        description: 'A flavorful biryani dish made with marinated beef and fragrant rice, cooked with spices and caramelized onions.',
        netQuantity: 'Full Plate',
        type: 'non-veg',
    },
    {
        id: 30,
        category: 'Indian Cuisine',
        imgUrl: 'https://media.istockphoto.com/id/1475065952/photo/traditional-shahi-haleem-or-halim-indian-halim-iftar-dish-haleem-bangladeshi-tasty-haleem.jpg?s=612x612&w=0&k=20&c=2RpiQer2wxlQ-GrfPY_WoobcZI_1MRKFazhm__iahqk=',
        name: 'Haleem',
        price: 180,
        currency: 'INR',
        ratings: 4.4,
        description: 'Thick stew made from wheat, barley, lentils, and meat (usually beef or mutton), slow-cooked with spices until it reaches a porridge-like consistency.',
        netQuantity: 'Regular Bowl',
        type: 'non-veg',
    }
];

export default FoodData;